apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:+vBN6C96BM1DF0tRfRFDEGadKeqLsKxGQdPXDcSJgvKJ/SO2,iv:OBtS7lTOKc1kDIN5DYS1Vb3f358AKEMVmkkH1LhSqFs=,tag:tJuJiWGVG+rXkHV6OEcyCg==,type:str]
    credentials.json: ENC[AES256_GCM,data:ZCBQ0WsPGSq2q02KEK9qmpAGehH5ohqw6AXzZ9L+HNypI+W8AuO1WCR/CP/1ApRQ8tAz3p/JHcHjXjrbMi1xPHF34z1g82YkvmyoxiJAYloyN28XDSz4sN1fV8mCdB+NO8xRlxnySdWhrwrkxMV41wTwEWNTUUkX/9unDJYtMWWFUJ2tpcbYcC6nzb83AKyz9ZTSVk9KhvDspDeoFX8PSBHPL2jJ1lpkoeLHsS4rNg==,iv:tprPl3LhRzIPaBmTPXxuZMzpV0Krd7Z39U5Ss9Bb860=,tag:tPRAgxhgMP3/I5ma+WijHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tv33nwd83c43aep9vuak00dngdhavv05x65t7p8jcw2mrurm94eqmgvzvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOW1FVnNodEh4Vjh4OFYx
            RzZzZzRnSnBZTE9iK3NYRUNaZlVoT01VQ1FJCmZhWXZlN2dRdFBWWmgzWm9HaWJw
            aGNsU2VDTHdMbE0wbzFSYVhSc2xQMEEKLS0tIE9XR0tmU1RWajM5c09idGNvVEsz
            TFdvTzB3RDh5Q1pzZXVkeHB5KzVZVEkKaJPujCpGd++pHd5p6/HVzcSUB3y28lAH
            28uV5zjCgU7XxlWuiT7kQ6fg5K6T+EfCMBwxZTlKmERoS31YR75qlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T12:59:36Z"
    mac: ENC[AES256_GCM,data:ost6OZSS2uiEHeA1b8jMj6tfkGb4DTpK3K5F9o62x9gENPkgGVLFvbhfZMwDV+OaT0AeapYxdXsc54EyCO1b22leoQWlfU1Qvm5v6Ppi35dRS1GzxvTsLaujGUjsnMO+ntimKX6LQEr5wmLBtljmUcrOoWjk6gq4Iy6Za7wKq2o=,iv:mXxx6D3lVJ/bYrE1+BNZFjAFxIu4HMwZPO6hmYHJ9pI=,tag:veqyBYgU+NufeiMnODJ/Sg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
