apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:g+R4889saThLpK6YUIdM5Emd9iquwo0eWzbZDOA53+I4rTdUA0F9pw==,iv:3joRMd6dw9VwmlZh0c77B2n1nFGIWnxJAve59r6tDQI=,tag:K65XmNiG3nK5yueLV+NZ4w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tv33nwd83c43aep9vuak00dngdhavv05x65t7p8jcw2mrurm94eqmgvzvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4Qm1VQjFLQmdiVkRmc1o0
            bW4xQmZVa2V5Vks5bHliN1B3b3N5Y0lpQ3dVCmtDMEtSZXFEN3hiZUpBYmE0NDRN
            R0JMTW5TYjZ5bGFtK1pjdCs1NkJaYXcKLS0tIEY5U2tHNmc5SzVLeDRkTzF0RTBP
            YkFCcUtzd0FJL1Y4ZE5sSEZ4TFdNa0EKUlubvo9Ku9QiZm03CfTAxoLjph9SFVoN
            lzEUtu5SVZdH8pxmuqelr5W+ziFVo4uouPpzPvtG2KY4HWSsi9FX7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T12:34:24Z"
    mac: ENC[AES256_GCM,data:lhikXV0LAgopS8OfvPzfpr0LaFDQx6WIhuin3mx1igd/si/+pcP7LD3/DQsdF5X9m8MUYov+MwVswhCpA5ucM1qCPVEc/WVvL7Q1MwpmqyuBUp0Jeyi3z/zA0EOGGAiKB8tmDoYtNmKUFA5Bjzwr3HvUHj4stuGC76/hsRKU/9I=,iv:JpukHYz+NJOXCEQ2XmVKkXOQSxU8FEWQZOYDmou32/c=,tag:XHf+B0sXi95dbrpKBD4a5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
