apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Po/3qp/nTvmAcHvKQvCr///xjIc6rkOdOjoVLYk8h5o=,iv:5IEeTrl01sdF2GSZ6TGES2hCEvZYu2hzM2/MBBVVYkY=,tag:gd1IM/qNVThfcPg6rsNuhg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tv33nwd83c43aep9vuak00dngdhavv05x65t7p8jcw2mrurm94eqmgvzvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2czlCVXU5bkYxTzZkQURa
            N2tzSlh1dVdocElpd2pSd0grd0RxYStEcUdzCjIwdkZmU0hCZ05GTU42SmtDZkQ2
            QmJRMmkvWFBBY1ZZdjRKUW0xOGpWVjAKLS0tIDNwN0FMTG52MkMzV1FSUTRKQ0dD
            SmNtK0VMTWs0QzlFOGN6ZkZKOHZTNEEKDa9Llf0bAcnsWmdk306vjgPXjjzcqaLk
            BPdQNBR/RHNvir23zm7S4YPnAT4c5pLDvqqaeuC3EUI8Y+tAhGx8ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T12:59:36Z"
    mac: ENC[AES256_GCM,data:LTO40ycatwxcUY7Oay/xphxrRGdcgiMSBp5v8RnZ9C7IdYc+nyuhw2owCqR/bl52QM2mbT9HJGX/iEdBEqdviWHGzKUJuOOseQCTzUdKzb8fzNp2OYHIY1C4Cmqd+7f/UrlvOeKde0MDnVWRx6CnOGxQMMvWqllHNio8RJRn7Qg=,iv:3w/11Yhtxmqp4sQXVnsfAbal7vJ9YjBfLmfXQNx+yB0=,tag:dWbjGsp1gg1HmbvGpEJY/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
