apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:Onold6UEkJNju8h5qaOCfGILpsWxwZZto1ytOKzTFgQ=,iv:8SaB8ZM5m8Su1AphRyhX5HaEE6y3k+lzOefDCXKSXa4=,tag:QjI6kpfh0Aw3JGBKZs9+qA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tv33nwd83c43aep9vuak00dngdhavv05x65t7p8jcw2mrurm94eqmgvzvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVmJDQkN0MWkrSkNrMjBF
            MENmL1JwUnN0Z08rdS9la1NEWDBjTThMOUJ3Ckk2MzhpdlVpWTBvL2VzQjRqMHF1
            Zk9QN1YxZVpwRFAxRzZjZ1pGcXdpd0kKLS0tIHBIanlMRFkrVUNiemR1Q3JBUGg5
            UEh5ZUNjeFBJc2NndHVaWXNYalpjQmMKHLF5Ajeiph6pX8oxgDDbV43R7BSm87bP
            0+ejloUG3dw2V56FjhIFmjhFNlOLRRoKJZONeeilSi+FZiFDuhHweA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-26T13:20:18Z"
    mac: ENC[AES256_GCM,data:x9MNfTFg7u/w3Et5lZPXUrVVs6Cjcu0+tIth0cnGl0lIboO3PKxok4njqXDoXd80Eiu7gYebhdcThDbs7BZawbO+AqnVsjg2CCgEBCQuEHucqG6rOHqCyZzhM+VOSclfSXBElpWVUKTaWWAoKKHn5/ZfIEkqkuwSjRT6VRZgmeE=,iv:myau7/vt1NM2EBWUGZ1WnRt10s/nh2vsNNmQ6rBgJHc=,tag:qJNc8jUKBCC/5BLhsYClHA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
